name: Unit Tests

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - name: Setup dotnet 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup dotnet 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run unit tests
      run: dotnet test --filter "FullyQualifiedName~UnitTests" 
